package com.example.javaquest._22_spring_web.Lesson18_SwaggerOpenApi;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.Properties;

public class _Lesson18_SwaggerOpenApi {

    public static void main(String[] args) throws Exception {

        System.out.println("=== LEKCJA 18: Swagger/OpenAPI PRZEZ springdoc (Spring Boot) ===");

        /*
         * ============================================================
         * 📦 REALIZACJA ZAPOWIEDZI Z _18_rest_api/Lesson18_OpenApiSwaggerIntro
         * ============================================================
         * `_18_rest_api/Lesson18` generowal specyfikacje OpenAPI 3.0
         * RECZNIE (jako text block YAML) - bo BEZ Spring MVC nie ma
         * NICZEGO, co moglo by ja WYGENEROWAC automatycznie. TU, W
         * Spring Boot, dodajemy JEDNA zaleznosc
         * (`springdoc-openapi-starter-webmvc-ui`) i CALA specyfikacja
         * generuje sie SAMA - PRZEZ SKANOWANIE adnotacji
         * `@RestController`/`@GetMapping`/`@RequestBody` itd. NA
         * DZIALAJACEJ aplikacji.
         *
         * Wystawiane SA 2 endpointy AUTOMATYCZNIE:
         * - `/v3/api-docs` - specyfikacja OpenAPI JAKO JSON.
         * - `/swagger-ui/index.html` - INTERAKTYWNA dokumentacja
         *   (Swagger UI) DO testowania endpointow W przegladarce.
         */
        System.out.println("springdoc-openapi = 1 zaleznosc -> /v3/api-docs (JSON) + /swagger-ui/index.html (interaktywna dokumentacja), BEZ recznego pisania YAML.");

        demonstrateAutoGeneratedOpenApiSpec();

        /*
         * ============================================================
         * 📌 PODSUMOWANIE
         * ============================================================
         * - `springdoc-openapi-starter-webmvc-ui` SKANUJE WSZYSTKIE
         *   `@RestController` W kontekscie Springa i BUDUJE specyfikacje
         *   OpenAPI 3 AUTOMATYCZNIE - ZERO recznego YAML/JSON.
         * - `/v3/api-docs` (JSON) MOZE byc uzyty PRZEZ narzedzia
         *   generujace klienty (OpenAPI Generator) LUB importowany DO
         *   Postmana (powiazanie z `_18_rest_api/Lesson17`).
         * - `/swagger-ui/index.html` DAJE interaktywny formularz DO
         *   testowania KAZDEGO endpointu WPROST z przegladarki - BEZ
         *   Postmana/curl.
         * - Bean `OpenAPI` (Z `@Bean`) POZWALA dostosowac METADANE
         *   (tytul/wersja/opis) - reszta (endpointy/parametry/DTO)
         *   generuje sie SAMA Z KODU kontrolerow.
         */
        System.out.println("\n=== KONIEC LEKCJI 18 ===");
    }

    record Task(String id, String title, boolean done) {
    }

    record CreateTaskRequest(String title) {
    }

    @RestController
    static class TaskController {
        @GetMapping("/tasks/{id}")
        Task getTask(@PathVariable String id) {
            return new Task(id, "Przykladowe zadanie", false);
        }

        @PostMapping("/tasks")
        Task createTask(@RequestBody CreateTaskRequest request) {
            return new Task("T1", request.title(), false);
        }
    }

    @Configuration
    static class OpenApiConfig {
        @Bean
        OpenAPI javaQuestOpenApi() {
            return new OpenAPI().info(new Info()
                    .title("JavaQuest Tasks API")
                    .version("1.0.0")
                    .description("Przykladowe API zadan - specyfikacja WYGENEROWANA automatycznie przez springdoc."));
        }
    }

    @SpringBootApplication
    static class SwaggerApp {
    }

    private static void demonstrateAutoGeneratedOpenApiSpec() throws Exception {
        System.out.println("\n=== AUTOMATYCZNIE WYGENEROWANA SPECYFIKACJA I SWAGGER UI ===");

        Properties props = new Properties();
        props.setProperty("server.port", "0");

        ConfigurableApplicationContext context = new SpringApplicationBuilder(SwaggerApp.class)
                .properties(props)
                .run();
        try {
            int port = context.getEnvironment().getProperty("local.server.port", Integer.class);

            HttpResponse<String> apiDocs = httpGet(port, "/v3/api-docs");
            System.out.println("GET /v3/api-docs -> status: " + apiDocs.statusCode());
            String body = apiDocs.body();
            System.out.println("Zawiera tytul 'JavaQuest Tasks API': " + body.contains("JavaQuest Tasks API"));
            System.out.println("Zawiera sciezke '/tasks/{id}' (WYKRYTA Z @GetMapping): " + body.contains("/tasks/{id}"));
            System.out.println("Zawiera sciezke '/tasks' (WYKRYTA Z @PostMapping): " + body.contains("\"/tasks\""));
            System.out.println("Fragment specyfikacji (pierwsze 300 znakow): " + body.substring(0, Math.min(300, body.length())) + "...");

            HttpResponse<String> swaggerUi = httpGet(port, "/swagger-ui/index.html");
            System.out.println("\nGET /swagger-ui/index.html -> status: " + swaggerUi.statusCode() + " (interaktywna strona Swagger UI, GOTOWA do testowania w przegladarce)");
        } finally {
            context.close();
        }
    }

    private static HttpResponse<String> httpGet(int port, String path) throws Exception {
        HttpClient client = HttpClient.newHttpClient();
        HttpRequest request = HttpRequest.newBuilder(URI.create("http://localhost:" + port + path)).GET().build();
        return client.send(request, HttpResponse.BodyHandlers.ofString());
    }
}
